"""Initial

Revision ID: <your_revision_id>
Revises: 
Create Date: <current_date_and_time>

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '<your_revision_id>'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videocards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.Index(
        'ix_videocards_id',
        sa.Column('id'), unique=False),
    sa.Index(
        'ix_videocards_name', sa.Column('name'), unique=False
    )
    )
    op.create_table('cpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('clock_speed', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
        sa.Index(
        'ix_cpus_id',
        sa.Column('id'), unique=False),
    sa.Index(
        'ix_cpus_name', sa.Column('name'), unique=False
    )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videocards')
    op.drop_table('cpus')
    # ### end Alembic commands ###